routes/admin.php
<?php

// Registered, activated, and is admin routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'role:admin', 'activity', 'twostep']], function () {

    // Route::resource('/users/deleted', 'SoftDeletesController', ['only' => ['index', 'show', 'update', 'destroy']]);

    Route::resource('users', 'UsersManagementController', [
        'names' => ['index'   => 'users', 'destroy' => 'user.destroy']
    ]);

    Route::get('users/{id}/edit/clubs','UsersManagementController@editClubs')->name('user.edit.clubs');
    Route::get('users/{id}/data','UsersManagementController@getUser');
    
    Route::get('users/{id}/verify', 'UsersManagementController@verify')->name('users.verify');
    Route::get('users/{id}/unverify', 'UsersManagementController@unverify')->name('users.unverify');

    // BLOCK USERS
    Route::get('blockedusers', 'UsersManagementController@indexBlockedUsers')->name('users.blocked.index');
    Route::get('blockedusers/{id}/unblock', 'UsersManagementController@unblock')->name('users.unblock');
    Route::get('users/{id}/block', 'UsersManagementController@block')->name('users.block');

    Route::post('search-users', 'UsersManagementController@search')->name('search-users');

    // Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    // Route::get('routes', 'AdminDetailsController@listRoutes');

    Route::namespace('Admin')->group(function () {
        Route::resource('config', 'ConfigController',['only' => ['index','store']]);
        Route::get('config/tyc','ConfigController@showTerms')->name('terms.edit');
        Route::post('config/tyc','ConfigController@storeTerms')->name('terms.store');
        Route::get('config/privacy','ConfigController@showPrivacy')->name('privacy.edit');
        Route::post('config/privacy','ConfigController@storePrivacy')->name('privacy.store');

        Route::resource('clubes', 'ClubesController');
        Route::post('clubes/{id}/verify', 'ClubesController@verify')->name('clubes.verify');
        Route::resource('sports', 'SportsController',['only' => ['index','edit','update','show','destroy']]);
        Route::resource('articles', 'ArticleController');

        Route::resource('publicidad', 'PublicidadController',['only' => ['index']]);
        Route::get('/api/publicidad','PublicidadController@getPublicidades');
        Route::post('/api/publicidad','PublicidadController@savePublicidad');
        Route::delete('/api/publicidad/{id}','PublicidadController@deletePublicidad');
        Route::delete('/api/publicidad/{id}/image','PublicidadController@deleteImageFromPublicidad');

        Route::resource('coupons', 'Stripe\CouponController');
        Route::resource('subscriptions', 'Stripe\SubscriptionController');
        Route::get('subscriptions/{idUser}/invoices', 'Stripe\SubscriptionController@invoices')->name('subscriptions.invoices');

        Route::resource('popularUsers', 'PopularUsersController',['only' => ['index','store']]);

        Route::resource('faqs', 'FaqsController',['only' => ['index','update','store','destroy']]);
        Route::get('admin/faqsByType','FaqsController@getFaqsByType');

        // SHOWCASE
        Route::get('/showcase','ShowCaseController@index')->name('admin.showcase.index');
        Route::get('/showcase/user/{id}','ShowCaseController@show')->name('admin.showcase.show');
        Route::post('/showcase/user','ShowCaseController@store')->name('admin.showcase.store');

        // REPORTS
        Route::get('admin/report','ReportController@index')->name('admin.reports.index');
        Route::get('admin/report/{id}','ReportController@show')->name('admin.reports.show');
        Route::get('admin/report/{id}/close','ReportController@close')->name('admin.reports.close');
        Route::get('admin/report/{id}/delete','ReportController@deleteReported')->name('admin.reports.deleteReported');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::resource('planes', 'Stripe\PlanesController');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Authentication Routes
Auth::routes(['verify' => true]);

Route::post('/registerScout', 'Auth\RegisterController@registerScout')->name('register.scout');
Route::post('/registerAthlete', 'Auth\RegisterController@registerAthlete')->name('register.athlete');

// WEB HOOK STRIPE
Route::post('stripe/webhook','Admin\Stripe\WebhookController@handleWebhook');

Route::get('locale/{locale}', 'WelcomeController@setLocale');

Route::group(['middleware' => ['web','auth']], function () {

    Route::get('api/updates', 'UpdatesController@getUpdates');

});

// Public Routes
Route::group(['middleware' => ['web', 'activity']], function () {

    // Locale

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
});


// Registered and Activated User Routes
Route::group(['middleware' => ['auth', 'activated','blocked', 'activity']], function () {
    
    Route::get('/planes/{id}/subscribe','PlanesController@show')->name('plan.show');
    Route::post('/planes/{id}/subscribe','PlanesController@saveSubscription')->name('plan.subscribe');
    Route::delete('/planes/{id}/subscribe','PlanesController@cancelSubscription')->name('plan.subscribe.cancel');
    Route::post('/api/planes/checkCoupon','PlanesController@checkPricePlanWithCoupon');

    // GET CURRENT SUBSCRIPTION
    Route::get('mySubscriptions','MySubcriptionsController@index')->name('mysubcriptions.index');
    Route::get('mySubscriptions/invoices','MySubcriptionsController@invoices')->name('mysubcriptions.invoices');
    Route::get('mySubscriptions/invoices/{invoice}','MySubcriptionsController@downloadInvoice');
    Route::get('mySubscriptions/paymentsMethods','MySubcriptionsController@paymentMethods')->name('mysubcriptions.paymentmethods');
    Route::get('mySubscriptions/paymentsMethods/create','MySubcriptionsController@createPaymentMethod')->name('mysubcriptions.paymentmethods.create');
    Route::post('mySubscriptions/paymentsMethods','MySubcriptionsController@storePaymentMethod')->name('mysubcriptions.paymentmethods.store');
    Route::get('mySubscriptions/paymentsMethods/{idCard}/default','MySubcriptionsController@setDefaultPaymentMethod')->name('mysubcriptions.paymentmethods.defaultcard');
    Route::delete('mySubscriptions/paymentsMethods/{id}','MySubcriptionsController@destroyPaymentMethod')->name('mysubcriptions.paymentmethods.destroy');
    
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', ['as'   => '{username}', 'uses' => 'ProfilesController@show']);

    Route::get('api/sports', 'Admin\SportsController@getSports');

    // Public Routes to see other profiles
    Route::get('p/profile/search', ['as'   => 'public.profile.search', 'uses' => 'PublicController@searchUser']);

    Route::get('p/profile/{uuid}', ['as'   => 'public.profile.show', 'uses' => 'PublicController@show']);

    Route::get('p/profile/{uuid}/follow', ['as'   => 'public.profile.follow', 'uses' => 'PublicController@follow']);
    Route::get('p/profile/{uuid}/unfollow', ['as'   => 'public.profile.unfollow', 'uses' => 'PublicController@unfollow']);

    Route::get('p/profile/{uuid}/addfavorite', ['as'   => 'public.profile.addFavorite', 'uses' => 'PublicController@addFavorite']);
    Route::get('p/profile/{uuid}/removefavorite', ['as'   => 'public.profile.removeFavorite', 'uses' => 'PublicController@removeFavorite']);

    
    // Route::get('api/favoritesusers','UpdatesController@getFavoritesUsers');
    Route::get('api/updatesFollowedFavoritesUsers','UpdatesController@getUpdatesFollowedFavoritesUsers');
    
    // Public View Recruitment
    Route::get('p/recruitment/{id}', ['as' => 'public.recruitment', 'uses' => 'UserController@showRecruitment']);
    
    Route::get('api/latestrecruitments', 'UserController@latestRecruitments');
    Route::get('api/recruitments/invitations','UserController@recruitmentsInvited');
    Route::post('api/recruitments/{id}/response','UserController@responseInvitationRecruitment');
    Route::post('api/recruitments/{id}/request','UserController@requestInvitationRecruitment');

    // POSTS
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::resource('posts','PostController',['only' => ['index','edit','create','destroy']]);
        Route::post('api/post','PostController@savePost');
        Route::put('api/post/{id}','PostController@updatePost');
        Route::delete('api/post/{id}', 'PostController@destroyPost');
    });
    
    Route::get('posts/{id}','PostController@show')->name('posts.show');
    Route::get('api/myposts','PostController@getMyPosts');
    Route::get('api/post/{id}','PostController@getPost');
    Route::post('api/post/{id}/comment','PostController@saveComment');
    Route::post('api/post/{id}/like','PostController@saveLike');


    // REPORTS
    Route::post('api/report','ReportController@report');

    // NOTIFICATIONS
    Route::get('/notifications','NotificationsController@index')->name('notifications.index');
    Route::get('/notifications/{id}/read','NotificationsController@markAsRead')->name('notifications.markAsRead');
    Route::get('/notifications/read/all','NotificationsController@markAllAsRead')->name('notifications.markAllAsRead');
});

// Registered, activated, and is current user routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'currentUser', 'activity', 'twostep']], function () {

    // User Profile and Account Routes
    Route::resource('profile', 'ProfilesController');

    Route::put('profile/{username}/updateUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserAccount']);
    Route::put('profile/{username}/updateUserPassword', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserPassword']);
    Route::delete('profile/{username}/deleteUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@deleteUserAccount']);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', ['uses' => 'ProfilesController@userProfileAvatar']);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);
    // Route to remove user avatar.
    Route::post('avatar/delete', ['as' => 'avatar.delete', 'uses' => 'ProfilesController@deleteAvatar']);

    Route::resource('favorites', 'FavoritesController');
    Route::resource('followed', 'FollowController');

    Route::get('messages','MessagesController@index')->name('messages.index');

    // SHOWCASE ATHLETE
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::post('api/athlete/{id}/showcase', 'ShowCaseController@store');
        Route::get('api/athlete/entitiesAvailables','ShowCaseController@getEntitiesPreferedAvailables');
        Route::get('api/clubs/types', 'ShowCaseController@getTypesClubs');
    });


    Route::namespace('Api')->group(function () {

        // GET CURRENT USER
        Route::get('api/user', 'UserController@getUser');

        // GET USERS TO SEND MESSAGES
        Route::get('api/usersToMessages', 'UserController@getUsersToMessages');

        // GET USERS BY TYPE
        Route::get('api/users', 'UserController@getUsers');

        // Images
        Route::post('api/user/media/upload', 'UserController@uploadMedia')->middleware('upload.photos');
        // Videos
        Route::post('api/user/videos/upload', 'UserController@uploadVideo')->middleware('upload.videos');

        Route::get('api/user/media', 'UserController@getMediaUser');
        Route::delete('api/user/media/delete/{id}', 'UserController@deleteMedia');

        Route::get('api/athlete/{id}', 'AthleteController@getAthlete');
        Route::post('api/athlete/{id}/sports', 'AthleteController@saveSportsAthlete');
        Route::post('api/athlete/{id}/clubs', 'AthleteController@saveClubsAthlete');

        Route::post('api/scout/{id}/sports', 'ScoutController@saveSports');
        Route::post('api/scout/{id}/clubs', 'ScoutController@saveClubsScout');

        
    });
    // MESSAGES
    Route::get('api/threads', 'MessagesController@getThreads');
    Route::post('api/threads', 'MessagesController@storeThread');
    Route::delete('api/threads/{id}', 'MessagesController@deleteThread');

app/Models/Media.php
<?php
namespace App\Models;

use Spatie\MediaLibrary\Models\Media as BaseMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Media extends BaseMedia
{

    use SoftDeletes;

    protected $appends = ['url','fullUrl'];

    protected $dates = [
        'deleted_at',
    ];
    
    public function getUrlAttribute()
    {
        return $this->getUrl();
    }

    public function getFullUrlAttribute()
    {
        return $this->getFullUrl();
    }

    public function getCreatedAtAttribute($input)
    {
        if ($input != null) {
            return Carbon::createFromFormat('Y-m-d H:i:s', $input)->format('d/m/Y H:i');
        } else {
            return '';
        }
    }

    public function report()
    {
        return $this->morphOne('App\Models\Report', 'reported');
    }
}

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use SoftDeletes;

    protected $table = 'posts';

    protected $dates = ['deleted_at'];
    
    protected $fillable = ['body','user_id'];

    protected $appends = [
        'timeAgo'
    ];
    
    public function user()
    {
        return $this->belongsTo('App\Models\User','user_id');
    }
    
    public function postmedia()
    {
        return $this->hasMany('App\Models\PostMedia','post_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\PostComment','post_id');
    }

    public function likes()
    {
        return $this->hasMany('App\Models\PostLikes','post_id');
    }

    public function report()
    {
        return $this->morphOne('App\Models\Report', 'reported');
    }

    public function getTimeAgoAttribute()
    {
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$this->created_at)->diffForHumans();
    }
    
}

resources/views/posts/create.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('posts.new-post') !!}
@endsection

@section('content')

    <edit-post :edit="false"></edit-post>

@endsection

@section('footer_scripts')

<link href="{{ asset('/assets/summernote/dist/summernote.css') }}" rel="stylesheet">
<link href="{{ asset('/assets/summernote/dist/summernote-bs4.css') }}" rel="stylesheet">
<script src="{{ asset('assets/summernote/dist/summernote.min.js') }}"></script>
<script src="{{ asset('assets/summernote/dist/summernote-bs4.min.js') }}"></script>

@endsection

resources/views/posts/edit.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('posts.editing-post') !!}
@endsection

@section('content')

    <edit-post :edit="true" :post="{{ $post }}"></edit-post>

@endsection

@section('footer_scripts')

<link href="{{ asset('/assets/summernote/dist/summernote.css') }}" rel="stylesheet">
<link href="{{ asset('/assets/summernote/dist/summernote-bs4.css') }}" rel="stylesheet">
<script src="{{ asset('assets/summernote/dist/summernote.min.js') }}"></script>
<script src="{{ asset('assets/summernote/dist/summernote-bs4.min.js') }}"></script>

@endsection

resources/views/posts/index.blade.php
@extends('layouts.app')

@section('template_title')
    {{ trans('posts.title') }}
@endsection

@section('template_fastload_css')
<style>
.text-prev {
  overflow: hidden;
  text-overflow: ellipsis;
  display: -webkit-box;
  line-height: 1.3rem;
  max-height: 3.9rem;
  -webkit-line-clamp: 1;
  -webkit-box-orient: vertical;
}
</style>
@endsection

@section('content')
<div class="w-full lg:w-5/6 mx-auto px-6 py-2">
    <div class="card-p">
            <div class="flex justify-between items-center pb-2 border-b mb-2">

                <div class="flex flex-wrap items-center">
                        <h4 class="font-bold"> {!! trans('posts.title') !!}</h4>

                        <div class="pl-4"> 
                            <span class="badge badge-primary rounded-full text-white">{{ trans('posts.postTotal') }}: {{ $posts->total() }} </span>
                        </div>
                </div>
                <div class="btn-group pull-right btn-group-xs">
                        <a class="btn btn-gray rounded-full" href="/posts/create">
                            <i class="fa fa-plus fa-fw" aria-hidden="true"></i>
                            {!! trans('posts.buttons.create-post') !!}
                        </a>
                </div>
            </div>

        <div class="w-full pt-4">
            @foreach ($posts as $p)
                <div class="border-b py-1">
                    <div class="flex flex-wrap justify-between items-center">
                        <div class="block w-auto sm:w-1/2 md:w-3/5"> 
                            <div>
                                <span class="text-prev"> {!! $p->body !!} </span>
                                <div class="text-xs text-gray-600">  
                                        {{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$p->created_at)->format('d/m/Y H:i')  }} 
                                </div>
                            </div>
                            <div class="flex">
                                <div class="flex items-center text-sm">
                                        <img class="icon-like" src="/img/icons/like.png" alt="Like">
                                        <span class="pl-2 text-like text-xs text-gray-900">
                                            <strong> {{ count($p->likes) }} </strong> 
                                            {{ trans_choice('dashboard.posts.likes',count($p->likes)) }}
                                        </span>
                                </div>
                                <div class="ml-4 flex items-center text-sm">
                                        <img class="icon-comment" src="/img/icons/comentario.png" alt="Comment">
                                        <span class="pl-2 text-comment text-xs text-gray-900">
                                                <strong> {{ count($p->comments) }} </strong> 
                                                {{ trans_choice('dashboard.posts.comments',count($p->comments)) }}
                                        </span>
                                </div>
                            </div>
                        </div>
                        <div class="w-auto">
                                <a class="btn btn-sm btn-outline-success rounded-full" href="{{ route('posts.show',[$p->id]) }}" data-toggle="tooltip" title="Show">
                                        {!! trans('posts.buttons.show') !!}
                                </a>
                                
                                <a class="btn btn-sm btn-outline-info rounded-full" href="{{ route('posts.edit',[$p->id]) }}" data-toggle="tooltip" title="Edit">
                                        {!! trans('posts.buttons.edit') !!}
                                </a>
                                {!! Form::open(array('url' => 'posts/' . $p->id, 'class' => 'form-inline', 'data-toggle' => 'tooltip', 'title' => 'Delete')) !!}
                                    {!! Form::hidden('_method', 'DELETE') !!}
                                    {!! Form::button(trans('posts.buttons.delete'), array('class' => 'btn btn-outline-danger rounded-full btn-sm','type' => 'button', 'style' =>'width: 100%;' ,'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete Post', 'data-message' => 'Are you sure you want to delete this post?')) !!}
                                {!! Form::close() !!}
                                    
                        </div>
                    </div>
                </div>
            @endforeach
        </div>

        @if(config('usersmanagement.enablePagination'))
            <div class="w-full mt-4">
                    {{ $posts->links() }}
            </div>
        @endif
    </div>

</div>

@include('modals.modal-delete')

@endsection

@section('footer_scripts')
@include('scripts.delete-modal-script')
    @if(config('clubes.tooltipsEnabled'))
        @include('scripts.tooltips')
    @endif

@endsection

resources/views/posts/show.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('posts.showing-post') !!}
@endsection

@section('content')

    @php
        $previousUrl = url()->previous();
        // dd($previousUrl);
    @endphp

    <show-post previous-url="{{ $previousUrl }}" :post="{{ $post }}"></show-post>

@endsection