routes/admin.php
<?php

// Registered, activated, and is admin routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'role:admin', 'activity', 'twostep']], function () {

    // Route::resource('/users/deleted', 'SoftDeletesController', ['only' => ['index', 'show', 'update', 'destroy']]);

    Route::resource('users', 'UsersManagementController', [
        'names' => ['index'   => 'users', 'destroy' => 'user.destroy']
    ]);

    Route::get('users/{id}/edit/clubs','UsersManagementController@editClubs')->name('user.edit.clubs');
    Route::get('users/{id}/data','UsersManagementController@getUser');
    
    Route::get('users/{id}/verify', 'UsersManagementController@verify')->name('users.verify');
    Route::get('users/{id}/unverify', 'UsersManagementController@unverify')->name('users.unverify');

    // BLOCK USERS
    Route::get('blockedusers', 'UsersManagementController@indexBlockedUsers')->name('users.blocked.index');
    Route::get('blockedusers/{id}/unblock', 'UsersManagementController@unblock')->name('users.unblock');
    Route::get('users/{id}/block', 'UsersManagementController@block')->name('users.block');

    Route::post('search-users', 'UsersManagementController@search')->name('search-users');

    // Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    // Route::get('routes', 'AdminDetailsController@listRoutes');

    Route::namespace('Admin')->group(function () {
        Route::resource('config', 'ConfigController',['only' => ['index','store']]);
        Route::get('config/tyc','ConfigController@showTerms')->name('terms.edit');
        Route::post('config/tyc','ConfigController@storeTerms')->name('terms.store');
        Route::get('config/privacy','ConfigController@showPrivacy')->name('privacy.edit');
        Route::post('config/privacy','ConfigController@storePrivacy')->name('privacy.store');

        Route::resource('clubes', 'ClubesController');
        Route::post('clubes/{id}/verify', 'ClubesController@verify')->name('clubes.verify');
        Route::resource('sports', 'SportsController',['only' => ['index','edit','update','show','destroy']]);
        Route::resource('articles', 'ArticleController');

        Route::resource('publicidad', 'PublicidadController',['only' => ['index']]);
        Route::get('/api/publicidad','PublicidadController@getPublicidades');
        Route::post('/api/publicidad','PublicidadController@savePublicidad');
        Route::delete('/api/publicidad/{id}','PublicidadController@deletePublicidad');
        Route::delete('/api/publicidad/{id}/image','PublicidadController@deleteImageFromPublicidad');

        Route::resource('coupons', 'Stripe\CouponController');
        Route::resource('subscriptions', 'Stripe\SubscriptionController');
        Route::get('subscriptions/{idUser}/invoices', 'Stripe\SubscriptionController@invoices')->name('subscriptions.invoices');

        Route::resource('popularUsers', 'PopularUsersController',['only' => ['index','store']]);

        Route::resource('faqs', 'FaqsController',['only' => ['index','update','store','destroy']]);
        Route::get('admin/faqsByType','FaqsController@getFaqsByType');

        // SHOWCASE
        Route::get('/showcase','ShowCaseController@index')->name('admin.showcase.index');
        Route::get('/showcase/user/{id}','ShowCaseController@show')->name('admin.showcase.show');
        Route::post('/showcase/user','ShowCaseController@store')->name('admin.showcase.store');

        // REPORTS
        Route::get('admin/report','ReportController@index')->name('admin.reports.index');
        Route::get('admin/report/{id}','ReportController@show')->name('admin.reports.show');
        Route::get('admin/report/{id}/close','ReportController@close')->name('admin.reports.close');
        Route::get('admin/report/{id}/delete','ReportController@deleteReported')->name('admin.reports.deleteReported');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::resource('planes', 'Stripe\PlanesController');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Authentication Routes
Auth::routes(['verify' => true]);

Route::post('/registerScout', 'Auth\RegisterController@registerScout')->name('register.scout');
Route::post('/registerAthlete', 'Auth\RegisterController@registerAthlete')->name('register.athlete');

// WEB HOOK STRIPE
Route::post('stripe/webhook','Admin\Stripe\WebhookController@handleWebhook');

Route::get('locale/{locale}', 'WelcomeController@setLocale');

Route::group(['middleware' => ['web','auth']], function () {

    Route::get('api/updates', 'UpdatesController@getUpdates');

});

// Public Routes
Route::group(['middleware' => ['web', 'activity']], function () {

    // Locale

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
});


// Registered and Activated User Routes
Route::group(['middleware' => ['auth', 'activated','blocked', 'activity']], function () {
    
    Route::get('/planes/{id}/subscribe','PlanesController@show')->name('plan.show');
    Route::post('/planes/{id}/subscribe','PlanesController@saveSubscription')->name('plan.subscribe');
    Route::delete('/planes/{id}/subscribe','PlanesController@cancelSubscription')->name('plan.subscribe.cancel');
    Route::post('/api/planes/checkCoupon','PlanesController@checkPricePlanWithCoupon');

    // GET CURRENT SUBSCRIPTION
    Route::get('mySubscriptions','MySubcriptionsController@index')->name('mysubcriptions.index');
    Route::get('mySubscriptions/invoices','MySubcriptionsController@invoices')->name('mysubcriptions.invoices');
    Route::get('mySubscriptions/invoices/{invoice}','MySubcriptionsController@downloadInvoice');
    Route::get('mySubscriptions/paymentsMethods','MySubcriptionsController@paymentMethods')->name('mysubcriptions.paymentmethods');
    Route::get('mySubscriptions/paymentsMethods/create','MySubcriptionsController@createPaymentMethod')->name('mysubcriptions.paymentmethods.create');
    Route::post('mySubscriptions/paymentsMethods','MySubcriptionsController@storePaymentMethod')->name('mysubcriptions.paymentmethods.store');
    Route::get('mySubscriptions/paymentsMethods/{idCard}/default','MySubcriptionsController@setDefaultPaymentMethod')->name('mysubcriptions.paymentmethods.defaultcard');
    Route::delete('mySubscriptions/paymentsMethods/{id}','MySubcriptionsController@destroyPaymentMethod')->name('mysubcriptions.paymentmethods.destroy');
    
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', ['as'   => '{username}', 'uses' => 'ProfilesController@show']);

    Route::get('api/sports', 'Admin\SportsController@getSports');

    // Public Routes to see other profiles
    Route::get('p/profile/search', ['as'   => 'public.profile.search', 'uses' => 'PublicController@searchUser']);

    Route::get('p/profile/{uuid}', ['as'   => 'public.profile.show', 'uses' => 'PublicController@show']);

    Route::get('p/profile/{uuid}/follow', ['as'   => 'public.profile.follow', 'uses' => 'PublicController@follow']);
    Route::get('p/profile/{uuid}/unfollow', ['as'   => 'public.profile.unfollow', 'uses' => 'PublicController@unfollow']);

    Route::get('p/profile/{uuid}/addfavorite', ['as'   => 'public.profile.addFavorite', 'uses' => 'PublicController@addFavorite']);
    Route::get('p/profile/{uuid}/removefavorite', ['as'   => 'public.profile.removeFavorite', 'uses' => 'PublicController@removeFavorite']);

    
    // Route::get('api/favoritesusers','UpdatesController@getFavoritesUsers');
    Route::get('api/updatesFollowedFavoritesUsers','UpdatesController@getUpdatesFollowedFavoritesUsers');
    
    // Public View Recruitment
    Route::get('p/recruitment/{id}', ['as' => 'public.recruitment', 'uses' => 'UserController@showRecruitment']);
    
    Route::get('api/latestrecruitments', 'UserController@latestRecruitments');
    Route::get('api/recruitments/invitations','UserController@recruitmentsInvited');
    Route::post('api/recruitments/{id}/response','UserController@responseInvitationRecruitment');
    Route::post('api/recruitments/{id}/request','UserController@requestInvitationRecruitment');

    // POSTS
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::resource('posts','PostController',['only' => ['index','edit','create','destroy']]);
        Route::post('api/post','PostController@savePost');
        Route::put('api/post/{id}','PostController@updatePost');
        Route::delete('api/post/{id}', 'PostController@destroyPost');
    });
    
    Route::get('posts/{id}','PostController@show')->name('posts.show');
    Route::get('api/myposts','PostController@getMyPosts');
    Route::get('api/post/{id}','PostController@getPost');
    Route::post('api/post/{id}/comment','PostController@saveComment');
    Route::post('api/post/{id}/like','PostController@saveLike');


    // REPORTS
    Route::post('api/report','ReportController@report');

    // NOTIFICATIONS
    Route::get('/notifications','NotificationsController@index')->name('notifications.index');
    Route::get('/notifications/{id}/read','NotificationsController@markAsRead')->name('notifications.markAsRead');
    Route::get('/notifications/read/all','NotificationsController@markAllAsRead')->name('notifications.markAllAsRead');
});

// Registered, activated, and is current user routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'currentUser', 'activity', 'twostep']], function () {

    // User Profile and Account Routes
    Route::resource('profile', 'ProfilesController');

    Route::put('profile/{username}/updateUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserAccount']);
    Route::put('profile/{username}/updateUserPassword', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserPassword']);
    Route::delete('profile/{username}/deleteUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@deleteUserAccount']);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', ['uses' => 'ProfilesController@userProfileAvatar']);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);
    // Route to remove user avatar.
    Route::post('avatar/delete', ['as' => 'avatar.delete', 'uses' => 'ProfilesController@deleteAvatar']);

    Route::resource('favorites', 'FavoritesController');
    Route::resource('followed', 'FollowController');

    Route::get('messages','MessagesController@index')->name('messages.index');

    // SHOWCASE ATHLETE
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::post('api/athlete/{id}/showcase', 'ShowCaseController@store');
        Route::get('api/athlete/entitiesAvailables','ShowCaseController@getEntitiesPreferedAvailables');
        Route::get('api/clubs/types', 'ShowCaseController@getTypesClubs');
    });


    Route::namespace('Api')->group(function () {

        // GET CURRENT USER
        Route::get('api/user', 'UserController@getUser');

        // GET USERS TO SEND MESSAGES
        Route::get('api/usersToMessages', 'UserController@getUsersToMessages');

        // GET USERS BY TYPE
        Route::get('api/users', 'UserController@getUsers');

        // Images
        Route::post('api/user/media/upload', 'UserController@uploadMedia')->middleware('upload.photos');
        // Videos
        Route::post('api/user/videos/upload', 'UserController@uploadVideo')->middleware('upload.videos');

        Route::get('api/user/media', 'UserController@getMediaUser');
        Route::delete('api/user/media/delete/{id}', 'UserController@deleteMedia');

        Route::get('api/athlete/{id}', 'AthleteController@getAthlete');
        Route::post('api/athlete/{id}/sports', 'AthleteController@saveSportsAthlete');
        Route::post('api/athlete/{id}/clubs', 'AthleteController@saveClubsAthlete');

        Route::post('api/scout/{id}/sports', 'ScoutController@saveSports');
        Route::post('api/scout/{id}/clubs', 'ScoutController@saveClubsScout');

        
    });
    // MESSAGES
    Route::get('api/threads', 'MessagesController@getThreads');
    Route::post('api/threads', 'MessagesController@storeThread');
    Route::delete('api/threads/{id}', 'MessagesController@deleteThread');

resources/views/admin/config/index.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('config.title') !!}
@endsection

@section('template_linked_css')
@endsection

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-11 col-md-9 col-lg-7">
                <div class="card-p">
                    <div class="flex flex-wrap border-b justify-between pb-1">
                        <h4 class="font-bold">  {!! trans('config.title') !!} </h4>
                    </div>

                    <div class="w-full pt-2">
                        {!! Form::open(array('route' => 'config.store', 'method' => 'POST', 'role' => 'form','class' => 'needs-validation')) !!}

                            {!! csrf_field() !!}

                            <div class="border-b pt-2 my-2 pb-1">
                                <h6 class="font-semibold"> {{ trans('config.globalConfig') }} </h6>
                            </div>
                            {{-- Verify Users --}}
                            <div class="col-12 mb-2 px-0 form-group has-feedback">
                                    <label class="col-12 flex items-center font-semibold">
                                        <input name="verifyUsers" class="mr-2 form-checkbox" {{ $verifyUsers->value ? 'checked' : '' }} type="checkbox">
                                        <span class="">  {{ trans('config.verifyUsers') }} </span>
                                    </label>    
                            </div>

                            {{-- Verify Scout Clubs --}}
                            <div class="col-12 mb-1 px-0 form-group has-feedback">
                                    <label class="col-12 flex items-center font-semibold">
                                        <input name="verifyScoutsClubs" class="mr-2 form-checkbox" {{ $verifyScoutsClubs->value ? 'checked' : '' }} type="checkbox">
                                        <span class="">  {{ trans('config.verifyScoutsClubs') }} </span>
                                    </label>    
                            </div>
                            <div class="mb-2 mx-2 rounded px-2 py-1 bg-gray-300 flex items-center">
                                <i class="fa fa-info-circle"></i>
                                <span class="pl-2"> {{ trans('config.infoVerifyUsers') }} </span>
                            </div>

                            {{-- Verify Clubs --}}
                            <div class="col-12 mb-1 px-0 form-group">
                                    <label class="col-12 flex items-center font-semibold">
                                        <input name="verifyClubs" class="mr-2 form-checkbox" {{ $verifyClubs->value ? 'checked' : '' }} type="checkbox">
                                        <span class="">  {{ trans('config.verifyClubs') }} </span>
                                    </label>    
                            </div>
                            <div class="mb-2 mx-2 rounded px-2 py-1 bg-gray-300 flex items-center">
                                <i class="fa fa-info-circle"></i>
                                <span class="pl-2"> {{ trans('config.infoVerifyClubs') }} </span>
                            </div>

                            {{-- Section Clubs in Home  --}}
                            <div class="col-12 mb-1 px-0 form-group">
                                    <label class="col-12 flex items-center font-semibold">
                                        <input name="sectionClubs" class="mr-2 form-checkbox" {{ ($sectionClubs && $sectionClubs->value) ? 'checked' : '' }} type="checkbox">
                                        <span class="">  {{ trans('config.showClubsInHome') }} </span>
                                    </label>    
                            </div>
                            {{-- Limit Images plan Athlete Free --}}
                            <div class="mb-1 mt-2 col-12 form-group">
                                <label for=""> {{ trans('config.limitImagesAtleteFree') }} </label>
                                {!! Form::text('limitImages', $limitImages, array('class' => 'w-full md:w-1/3 lg:w-1/4 form-control' )) !!} 
                            </div>
                            {{-- Limit Images plan SCOUT Free --}}
                            <div class="mb-1 mt-2 col-12 form-group">
                                    <label for=""> {{ trans('config.limitImagesScoutFree') }} </label>
                                    {!! Form::text('limitImagesScout', $limitImagesScout, array('class' => 'w-full md:w-1/3 lg:w-1/4 form-control' )) !!} 
                                </div>


                            <div class="border-b pt-2 my-2 pb-1">
                                <h6 class="font-semibold"> {{ trans('config.contactInfo') }} </h6>
                            </div>
                            <div class="row col-12 px-0">
                                <div class="col-12 col-md-6 form-group">
                                        <label for=""> {{ trans('config.contactEmail') }} </label>
                                        {!! Form::text('email', $email, array('class' => 'form-control' )) !!} 
                                    </div>
                                <div class="col-12 col-md-6 form-group">
                                    <label for=""> {{ trans('config.contactPhone') }} </label>
                                    {!! Form::text('phone', $phone, array('class' => 'form-control' )) !!} 
                                </div>
                            </div>


                            <div class="w-full flex flex-wrap justify-between items-end">
                                <div>
                                    <a class="btn btn-sm btn-outline-secondary rounded-full mr-1" href="{{url('/config/tyc')}}"> 
                                        <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
                                        <span>{{ trans('config.terms') }} </span>
                                    </a>
                                    <a class="btn btn-sm btn-outline-secondary rounded-full mr-1" href="{{url('/config/privacy')}}"> 
                                        <i class="fa fa-pencil fa-fw" aria-hidden="true"></i>
                                        <span>{{ trans('config.privacy') }} </span>
                                    </a>
                                </div>
                                <div>
                                    {!! Form::button(trans('config.save'), array('class' => 'btn btn-success rounded-full px-6','type' => 'submit' )) !!}
                                </div>
                            </div>
                            {!! Form::close() !!}
                    </div>

                </div>
            </div>
        
        
        </div>
    </div>

@endsection

@section('footer_scripts')

@endsection

resources/views/admin/config/privacy.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('config.title') !!}
@endsection

@section('template_linked_css')
<style>
.filters-terms button {
    padding: 0.4rem 1rem;
    color: black;
}
.filters-terms button.active {
    padding: 0.4rem 1rem;
    background-color: black;
    color: white;
}
</style>
@endsection

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="w-11/12 lg:w-4/5">
                <div class="card-p">
                    <div class="flex justify-between items-center pb-2 border-b mb-2">
                        <h4 class="font-bold">  {!! trans('config.privacy') !!} </h4>
                        <div>
                            <a href="{{ route('config.index') }}" class="btn btn-light btn-sm float-right" title="{{ trans('config.back-config') }}">
                                <i class="fa fa-fw fa-reply-all" aria-hidden="true"></i>
                                {!! trans('config.back-to-config') !!}
                            </a>
                        </div>
                    </div>

                    <div class="w-full pt-4">
                        {!! Form::open(array('route' => 'privacy.store', 'method' => 'POST', 'role' => 'form','class' => 'needs-validation')) !!}

                            {!! csrf_field() !!}
                            
                            <div class="mb-4 flex filters-terms">
                                    <button class="active english"> EN </button>
                                    <button class="spanish"> ES </button>
                                </div>

                            <div id="privacyEn" class="col-12 px-0 form-group">    
                                    {!! Form::textarea('privacy', $privacy, array('maxlength' => '50000','rows' => '14','class' => 'summernote form-control')) !!}  
                            </div>
                            <div id="privacyEs" class="hidden col-12 px-0 form-group">
                                    {!! Form::textarea('privacy_es', $privacy_es, array('maxlength' => '50000','rows' => '14','class' => 'summernote form-control')) !!}  
                            </div>

                            <div class="w-full flex justify-end">
                                {!! Form::button(trans('config.save'), array('class' => 'btn btn-success rounded-full px-6','type' => 'submit' )) !!}
                            </div>
                            {!! Form::close() !!}
                    </div>

                </div>
            </div>
        
        
        </div>
    </div>

@endsection

@section('footer_scripts')
<link href="{{ asset('/assets/summernote/dist/summernote.css') }}" rel="stylesheet">
<link href="{{ asset('/assets/summernote/dist/summernote-bs4.css') }}" rel="stylesheet">
<script src="{{ asset('assets/summernote/dist/summernote.min.js') }}"></script>
<script src="{{ asset('assets/summernote/dist/summernote-bs4.min.js') }}"></script>
<script>
// $(document).ready(function() {
  $('.summernote').summernote();

  $('.filters-terms button').on('click', function (e) {
        e.preventDefault();
        if ($(this).hasClass('english') && !$(this).hasClass('active')) {
            $(this).addClass('active');
            $('button.spanish').removeClass('active');
            $('#privacyEs').addClass('hidden');
            $('#privacyEn').removeClass('hidden');

        } else if ($(this).hasClass('spanish') && !$(this).hasClass('active')) {
            $(this).addClass('active');
            $('button.english').removeClass('active');
            $('#privacyEn').addClass('hidden');
            $('#privacyEs').removeClass('hidden');
        }
    })
// });
</script>
@endsection

resources/views/admin/config/terms.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('config.title') !!}
@endsection

@section('template_linked_css')
<style>
.filters-terms button {
    padding: 0.4rem 1rem;
    color: black;
}
.filters-terms button.active {
    padding: 0.4rem 1rem;
    background-color: black;
    color: white;
}
</style>
@endsection

@section('content')

    <div class="container">
        <div class="row justify-content-center">
            <div class="w-11/12 lg:w-4/5">
                <div class="card-p">
                    <div class="flex justify-between items-center pb-2 border-b mb-2">
                        <h4 class="font-bold">  {!! trans('config.terms') !!} </h4>
                        <div>
                            <a href="{{ route('config.index') }}" class="btn btn-light btn-sm float-right" title="{{ trans('config.back-config') }}">
                                <i class="fa fa-fw fa-reply-all" aria-hidden="true"></i>
                                {!! trans('config.back-to-config') !!}
                            </a>
                        </div>
                    </div>

                    <div class="w-full pt-4">
                        {!! Form::open(array('route' => 'terms.store', 'method' => 'POST', 'role' => 'form','class' => 'needs-validation')) !!}

                            {!! csrf_field() !!}

                            <div class="mb-4 flex filters-terms">
                                <button class="active english"> EN </button>
                                <button class="spanish"> ES </button>
                            </div>

                            <div id="termsEn" class="col-12 px-0 form-group">
                                    {{-- <label for="terms"> {{ trans('config.labelTermEnglish') }} </label>     --}}
                                    {!! Form::textarea('terms', $terms, array('maxlength' => '50000','rows' => '14','class' => 'summernote form-control')) !!}  
                            </div>

                            <div id="termsEs" class="hidden col-12 px-0 form-group">
                                    {{-- <label for="terms_es"> {{ trans('config.labelTermSpanish') }} </label>     --}}
                                    {!! Form::textarea('terms_es', $terms_es, array('maxlength' => '50000','rows' => '14','class' => 'summernote form-control')) !!}  
                            </div>

                            <div class="w-full flex justify-end">
                                {!! Form::button(trans('config.save'), array('class' => 'btn btn-success rounded-full px-6','type' => 'submit' )) !!}
                            </div>
                            {!! Form::close() !!}
                    </div>

                </div>
            </div>
        
        
        </div>
    </div>

@endsection

@section('footer_scripts')
<link href="{{ asset('/assets/summernote/dist/summernote.css') }}" rel="stylesheet">
<link href="{{ asset('/assets/summernote/dist/summernote-bs4.css') }}" rel="stylesheet">
<script src="{{ asset('assets/summernote/dist/summernote.min.js') }}"></script>
<script src="{{ asset('assets/summernote/dist/summernote-bs4.min.js') }}"></script>
<script>
// $(document).ready(function() {
    
    $('.summernote').summernote();

    $('.filters-terms button').on('click', function (e) {
        e.preventDefault();
        if ($(this).hasClass('english') && !$(this).hasClass('active')) {
            $(this).addClass('active');
            $('button.spanish').removeClass('active');
            $('#termsEs').addClass('hidden');
            $('#termsEn').removeClass('hidden');

        } else if ($(this).hasClass('spanish') && !$(this).hasClass('active')) {
            $(this).addClass('active');
            $('button.english').removeClass('active');
            $('#termsEn').addClass('hidden');
            $('#termsEs').removeClass('hidden');
        }
    })
// });
</script>
@endsection