routes/admin.php
<?php

// Registered, activated, and is admin routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'role:admin', 'activity', 'twostep']], function () {

    // Route::resource('/users/deleted', 'SoftDeletesController', ['only' => ['index', 'show', 'update', 'destroy']]);

    Route::resource('users', 'UsersManagementController', [
        'names' => ['index'   => 'users', 'destroy' => 'user.destroy']
    ]);

    Route::get('users/{id}/edit/clubs','UsersManagementController@editClubs')->name('user.edit.clubs');
    Route::get('users/{id}/data','UsersManagementController@getUser');
    
    Route::get('users/{id}/verify', 'UsersManagementController@verify')->name('users.verify');
    Route::get('users/{id}/unverify', 'UsersManagementController@unverify')->name('users.unverify');

    // BLOCK USERS
    Route::get('blockedusers', 'UsersManagementController@indexBlockedUsers')->name('users.blocked.index');
    Route::get('blockedusers/{id}/unblock', 'UsersManagementController@unblock')->name('users.unblock');
    Route::get('users/{id}/block', 'UsersManagementController@block')->name('users.block');

    Route::post('search-users', 'UsersManagementController@search')->name('search-users');

    // Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    // Route::get('routes', 'AdminDetailsController@listRoutes');

    Route::namespace('Admin')->group(function () {
        Route::resource('config', 'ConfigController',['only' => ['index','store']]);
        Route::get('config/tyc','ConfigController@showTerms')->name('terms.edit');
        Route::post('config/tyc','ConfigController@storeTerms')->name('terms.store');
        Route::get('config/privacy','ConfigController@showPrivacy')->name('privacy.edit');
        Route::post('config/privacy','ConfigController@storePrivacy')->name('privacy.store');

        Route::resource('clubes', 'ClubesController');
        Route::post('clubes/{id}/verify', 'ClubesController@verify')->name('clubes.verify');
        Route::resource('sports', 'SportsController',['only' => ['index','edit','update','show','destroy']]);
        Route::resource('articles', 'ArticleController');

        Route::resource('publicidad', 'PublicidadController',['only' => ['index']]);
        Route::get('/api/publicidad','PublicidadController@getPublicidades');
        Route::post('/api/publicidad','PublicidadController@savePublicidad');
        Route::delete('/api/publicidad/{id}','PublicidadController@deletePublicidad');
        Route::delete('/api/publicidad/{id}/image','PublicidadController@deleteImageFromPublicidad');

        Route::resource('coupons', 'Stripe\CouponController');
        Route::resource('subscriptions', 'Stripe\SubscriptionController');
        Route::get('subscriptions/{idUser}/invoices', 'Stripe\SubscriptionController@invoices')->name('subscriptions.invoices');

        Route::resource('popularUsers', 'PopularUsersController',['only' => ['index','store']]);

        Route::resource('faqs', 'FaqsController',['only' => ['index','update','store','destroy']]);
        Route::get('admin/faqsByType','FaqsController@getFaqsByType');

        // SHOWCASE
        Route::get('/showcase','ShowCaseController@index')->name('admin.showcase.index');
        Route::get('/showcase/user/{id}','ShowCaseController@show')->name('admin.showcase.show');
        Route::post('/showcase/user','ShowCaseController@store')->name('admin.showcase.store');

        // REPORTS
        Route::get('admin/report','ReportController@index')->name('admin.reports.index');
        Route::get('admin/report/{id}','ReportController@show')->name('admin.reports.show');
        Route::get('admin/report/{id}/close','ReportController@close')->name('admin.reports.close');
        Route::get('admin/report/{id}/delete','ReportController@deleteReported')->name('admin.reports.deleteReported');

        Route::prefix('admin')->name('admin.')->group(function () {
            Route::resource('planes', 'Stripe\PlanesController');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
| Middleware options can be located in `app/Http/Kernel.php`
|
*/

// Authentication Routes
Auth::routes(['verify' => true]);

Route::post('/registerScout', 'Auth\RegisterController@registerScout')->name('register.scout');
Route::post('/registerAthlete', 'Auth\RegisterController@registerAthlete')->name('register.athlete');

// WEB HOOK STRIPE
Route::post('stripe/webhook','Admin\Stripe\WebhookController@handleWebhook');

Route::get('locale/{locale}', 'WelcomeController@setLocale');

Route::group(['middleware' => ['web','auth']], function () {

    Route::get('api/updates', 'UpdatesController@getUpdates');

});

// Public Routes
Route::group(['middleware' => ['web', 'activity']], function () {

    // Locale

    // Activation Routes
    Route::get('/activate', ['as' => 'activate', 'uses' => 'Auth\ActivateController@initial']);

    Route::get('/activate/{token}', ['as' => 'authenticated.activate', 'uses' => 'Auth\ActivateController@activate']);
    Route::get('/activation', ['as' => 'authenticated.activation-resend', 'uses' => 'Auth\ActivateController@resend']);
    Route::get('/exceeded', ['as' => 'exceeded', 'uses' => 'Auth\ActivateController@exceeded']);

    // Socialite Register Routes
    Route::get('/social/redirect/{provider}', ['as' => 'social.redirect', 'uses' => 'Auth\SocialController@getSocialRedirect']);
    Route::get('/social/handle/{provider}', ['as' => 'social.handle', 'uses' => 'Auth\SocialController@getSocialHandle']);

    // Route to for user to reactivate their user deleted account.
    Route::get('/re-activate/{token}', ['as' => 'user.reactivate', 'uses' => 'RestoreUserController@userReActivate']);
});


// Registered and Activated User Routes
Route::group(['middleware' => ['auth', 'activated','blocked', 'activity']], function () {
    
    Route::get('/planes/{id}/subscribe','PlanesController@show')->name('plan.show');
    Route::post('/planes/{id}/subscribe','PlanesController@saveSubscription')->name('plan.subscribe');
    Route::delete('/planes/{id}/subscribe','PlanesController@cancelSubscription')->name('plan.subscribe.cancel');
    Route::post('/api/planes/checkCoupon','PlanesController@checkPricePlanWithCoupon');

    // GET CURRENT SUBSCRIPTION
    Route::get('mySubscriptions','MySubcriptionsController@index')->name('mysubcriptions.index');
    Route::get('mySubscriptions/invoices','MySubcriptionsController@invoices')->name('mysubcriptions.invoices');
    Route::get('mySubscriptions/invoices/{invoice}','MySubcriptionsController@downloadInvoice');
    Route::get('mySubscriptions/paymentsMethods','MySubcriptionsController@paymentMethods')->name('mysubcriptions.paymentmethods');
    Route::get('mySubscriptions/paymentsMethods/create','MySubcriptionsController@createPaymentMethod')->name('mysubcriptions.paymentmethods.create');
    Route::post('mySubscriptions/paymentsMethods','MySubcriptionsController@storePaymentMethod')->name('mysubcriptions.paymentmethods.store');
    Route::get('mySubscriptions/paymentsMethods/{idCard}/default','MySubcriptionsController@setDefaultPaymentMethod')->name('mysubcriptions.paymentmethods.defaultcard');
    Route::delete('mySubscriptions/paymentsMethods/{id}','MySubcriptionsController@destroyPaymentMethod')->name('mysubcriptions.paymentmethods.destroy');
    
    // Activation Routes
    Route::get('/activation-required', ['uses' => 'Auth\ActivateController@activationRequired'])->name('activation-required');
    Route::get('/logout', ['uses' => 'Auth\LoginController@logout'])->name('logout');

    //  Homepage Route - Redirect based on user role is in controller.
    Route::get('/home', ['as' => 'home',   'uses' => 'UserController@index']);

    // Show users profile - viewable by other users.
    Route::get('profile/{username}', ['as'   => '{username}', 'uses' => 'ProfilesController@show']);

    Route::get('api/sports', 'Admin\SportsController@getSports');

    // Public Routes to see other profiles
    Route::get('p/profile/search', ['as'   => 'public.profile.search', 'uses' => 'PublicController@searchUser']);

    Route::get('p/profile/{uuid}', ['as'   => 'public.profile.show', 'uses' => 'PublicController@show']);

    Route::get('p/profile/{uuid}/follow', ['as'   => 'public.profile.follow', 'uses' => 'PublicController@follow']);
    Route::get('p/profile/{uuid}/unfollow', ['as'   => 'public.profile.unfollow', 'uses' => 'PublicController@unfollow']);

    Route::get('p/profile/{uuid}/addfavorite', ['as'   => 'public.profile.addFavorite', 'uses' => 'PublicController@addFavorite']);
    Route::get('p/profile/{uuid}/removefavorite', ['as'   => 'public.profile.removeFavorite', 'uses' => 'PublicController@removeFavorite']);

    
    // Route::get('api/favoritesusers','UpdatesController@getFavoritesUsers');
    Route::get('api/updatesFollowedFavoritesUsers','UpdatesController@getUpdatesFollowedFavoritesUsers');
    
    // Public View Recruitment
    Route::get('p/recruitment/{id}', ['as' => 'public.recruitment', 'uses' => 'UserController@showRecruitment']);
    
    Route::get('api/latestrecruitments', 'UserController@latestRecruitments');
    Route::get('api/recruitments/invitations','UserController@recruitmentsInvited');
    Route::post('api/recruitments/{id}/response','UserController@responseInvitationRecruitment');
    Route::post('api/recruitments/{id}/request','UserController@requestInvitationRecruitment');

    // POSTS
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::resource('posts','PostController',['only' => ['index','edit','create','destroy']]);
        Route::post('api/post','PostController@savePost');
        Route::put('api/post/{id}','PostController@updatePost');
        Route::delete('api/post/{id}', 'PostController@destroyPost');
    });
    
    Route::get('posts/{id}','PostController@show')->name('posts.show');
    Route::get('api/myposts','PostController@getMyPosts');
    Route::get('api/post/{id}','PostController@getPost');
    Route::post('api/post/{id}/comment','PostController@saveComment');
    Route::post('api/post/{id}/like','PostController@saveLike');


    // REPORTS
    Route::post('api/report','ReportController@report');

    // NOTIFICATIONS
    Route::get('/notifications','NotificationsController@index')->name('notifications.index');
    Route::get('/notifications/{id}/read','NotificationsController@markAsRead')->name('notifications.markAsRead');
    Route::get('/notifications/read/all','NotificationsController@markAllAsRead')->name('notifications.markAllAsRead');
});

// Registered, activated, and is current user routes.
Route::group(['middleware' => ['auth', 'activated','blocked', 'currentUser', 'activity', 'twostep']], function () {

    // User Profile and Account Routes
    Route::resource('profile', 'ProfilesController');

    Route::put('profile/{username}/updateUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserAccount']);
    Route::put('profile/{username}/updateUserPassword', ['as'   => '{username}', 'uses' => 'ProfilesController@updateUserPassword']);
    Route::delete('profile/{username}/deleteUserAccount', ['as'   => '{username}', 'uses' => 'ProfilesController@deleteUserAccount']);

    // Route to show user avatar
    Route::get('images/profile/{id}/avatar/{image}', ['uses' => 'ProfilesController@userProfileAvatar']);

    // Route to upload user avatar.
    Route::post('avatar/upload', ['as' => 'avatar.upload', 'uses' => 'ProfilesController@upload']);
    // Route to remove user avatar.
    Route::post('avatar/delete', ['as' => 'avatar.delete', 'uses' => 'ProfilesController@deleteAvatar']);

    Route::resource('favorites', 'FavoritesController');
    Route::resource('followed', 'FollowController');

    Route::get('messages','MessagesController@index')->name('messages.index');

    // SHOWCASE ATHLETE
    Route::group(['middleware' => ['role:athlete']], function () {
        Route::post('api/athlete/{id}/showcase', 'ShowCaseController@store');
        Route::get('api/athlete/entitiesAvailables','ShowCaseController@getEntitiesPreferedAvailables');
        Route::get('api/clubs/types', 'ShowCaseController@getTypesClubs');
    });


    Route::namespace('Api')->group(function () {

        // GET CURRENT USER
        Route::get('api/user', 'UserController@getUser');

        // GET USERS TO SEND MESSAGES
        Route::get('api/usersToMessages', 'UserController@getUsersToMessages');

        // GET USERS BY TYPE
        Route::get('api/users', 'UserController@getUsers');

        // Images
        Route::post('api/user/media/upload', 'UserController@uploadMedia')->middleware('upload.photos');
        // Videos
        Route::post('api/user/videos/upload', 'UserController@uploadVideo')->middleware('upload.videos');

        Route::get('api/user/media', 'UserController@getMediaUser');
        Route::delete('api/user/media/delete/{id}', 'UserController@deleteMedia');

        Route::get('api/athlete/{id}', 'AthleteController@getAthlete');
        Route::post('api/athlete/{id}/sports', 'AthleteController@saveSportsAthlete');
        Route::post('api/athlete/{id}/clubs', 'AthleteController@saveClubsAthlete');

        Route::post('api/scout/{id}/sports', 'ScoutController@saveSports');
        Route::post('api/scout/{id}/clubs', 'ScoutController@saveClubsScout');

        
    });
    // MESSAGES
    Route::get('api/threads', 'MessagesController@getThreads');
    Route::post('api/threads', 'MessagesController@storeThread');
    Route::delete('api/threads/{id}', 'MessagesController@deleteThread');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\Translatable\HasTranslations;

class Article extends Model implements HasMedia
{

    use HasMediaTrait, HasTranslations;

    protected $table = 'articles';

    protected $fillable = ['title', 'resume', 'body', 'user_id'];

    public $translatable = ['title', 'resume', 'body'];

    protected $appends = [
        'image',
        'timeAgo',
        'hasImage'
    ];

    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id');
    }

    public function getImageAttribute()
    {
        $img = $this->getMedia('article');
        if (count($img) == 0) {
            $img = asset('img/article.png');
        } else {
            $img = $img->last()->getFullUrl();
        }
        return $img;
    }

    public function getHasImageAttribute()
    {
        $img = $this->getMedia('article');
        return count($img) > 0;
    }

    public function getTimeAgoAttribute()
    {
        if ($this->updated_at == null) return null;
        return \Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $this->updated_at)->diffForHumans();
    }
}

app/Models/Media.php
<?php
namespace App\Models;

use Spatie\MediaLibrary\Models\Media as BaseMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

class Media extends BaseMedia
{

    use SoftDeletes;

    protected $appends = ['url','fullUrl'];

    protected $dates = [
        'deleted_at',
    ];
    
    public function getUrlAttribute()
    {
        return $this->getUrl();
    }

    public function getFullUrlAttribute()
    {
        return $this->getFullUrl();
    }

    public function getCreatedAtAttribute($input)
    {
        if ($input != null) {
            return Carbon::createFromFormat('Y-m-d H:i:s', $input)->format('d/m/Y H:i');
        } else {
            return '';
        }
    }

    public function report()
    {
        return $this->morphOne('App\Models\Report', 'reported');
    }
}

resources/views/admin/articles/index.blade.php
@extends('layouts.app')

@section('template_title')
    {!! trans('articles.showing-all-articles') !!}
@endsection

@section('template_linked_css')
    @if(config('articles.enabledDatatablesJs'))
        <link rel="stylesheet" type="text/css" href="{{ config('articles.datatablesCssCDN') }}">
    @endif
    <style type="text/css" media="screen">
        .users-table {
            border: 0;
        }
        .users-table tr td:first-child {
            padding-left: 15px;
        }
        .users-table tr td:last-child {
            padding-right: 15px;
        }
        .users-table.table-responsive,
        .users-table.table-responsive table {
            margin-bottom: 0;
        }
    </style>
@endsection

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card-p">

                        <div class="flex flex-wrap justify-between items-center pb-2 border-b mb-2">
                            <div class="flex flex-wrap items-center">
                                <h4 class="font-bold pr-4"> {!! trans('articles.showing-all-articles') !!}</h4>

                                <div class="w-auto"> 
                                    <span class="badge badge-primary rounded-full text-white">{{ trans('articles.articleTotal') }}: {{ $articles->total() }} </span>
                                </div>
                            </div>

                            <div class="mt-2 sm:mt-0 btn-group btn-group-xs">
                                {{-- <div class="dropdown-menu dropdown-menu-right"> --}}
                                    <a class="btn btn-gray rounded-full" href="/articles/create">
                                        <i class="fa fa-plus fa-fw" aria-hidden="true"></i>
                                        {!! trans('articles.buttons.create-new') !!}
                                    </a>
                                {{-- </div> --}}
                            </div>
                    </div>

                    <div class="w-full">

                        {{-- @if(config('articles.enableSearchUsers'))
                            @include('partials.search-users-form')
                        @endif --}}

                        <div class="table-responsive users-table">
                            <table class="table table-striped table-sm vertical-middle data-table primary">
                                
                                <thead class="thead">
                                    <tr>
                                        <th>{!! trans('articles.articles-table.title') !!}</th>
                                        <th>{!! trans('articles.articles-table.created') !!}</th>
                                        {{-- <th>{!! trans('articles.articles-table.updated') !!}</th> --}}
                                        <th>{!! trans('articles.articles-table.actions') !!}</th>
                                    </tr>
                                </thead>
                                <tbody id="users_table">
                                    @foreach($articles as $c)
                                        <tr>
                                            <td style="min-width: 350px;" class="flex items-center">
                                                @if($c->image) 
                                                  <img class="rounded-lg border border-gray-400 img-fluid h-16 w-20 object-cover" src="{{ $c->image }}" alt="{{ $c->title }}">
                                                @endif
                                                <span class="pl-2"> {{$c->title}} </span> 
                                            </td>
                                            <td>
                                                @if(isset($c->created_at))
                                                    {{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$c->created_at)->format(config('settings.formatDate'))  }}
                                                @endif
                                            </td>
                                            {{-- <td>{{$c->updated_at}}</td> --}}
                                            
                                            <td class="buttons-actions">
                                                <a class="btn btn-sm btn-outline-success rounded-full" href="{{ route('articles.show',[$c->id]) }}" data-toggle="tooltip" title="Show">
                                                    {!! trans('articles.buttons.show') !!}
                                                </a>
                                            
                                                <a class="btn btn-sm btn-outline-info rounded-full" href="{{ route('articles.edit',[$c->id]) }}" data-toggle="tooltip" title="Edit">
                                                    {!! trans('articles.buttons.edit') !!}
                                                </a>
                                                {!! Form::open(array('url' => 'articles/' . $c->id, 'class' => 'form-inline', 'data-toggle' => 'tooltip', 'title' => 'Delete')) !!}
                                                    {!! Form::hidden('_method', 'DELETE') !!}
                                                    {!! Form::button(trans('articles.buttons.delete'), array('class' => 'btn btn-outline-danger btn-sm rounded-full','type' => 'button','data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete Article', 'data-message' => 'Are you sure you want to delete this article ?')) !!}
                                                {!! Form::close() !!}

                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>

                            </table>

                            
                        </div>
                        @if(config('usersmanagement.enablePagination'))
                            <div class="w-full mt-4">
                                {{ $articles->links() }}
                            </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>

    @include('modals.modal-delete')

@endsection

@section('footer_scripts')
    @if ((count($articles) > config('articles.datatablesJsStartCount')) && config('articles.enabledDatatablesJs'))
        @include('scripts.datatables')
    @endif
    @include('scripts.delete-modal-script')
    @include('scripts.save-modal-script')
    @if(config('articles.tooltipsEnabled'))
        @include('scripts.tooltips')
    @endif
    {{-- @if(config('articles.enableSearchUsers'))
        @include('scripts.search-users')
    @endif --}}
@endsection

resources/views/admin/articles/show.blade.php
@extends('layouts.app')

@section('template_title')
  {!! trans('articles.showing-article') !!}
@endsection

@section('content')

  <div class="container">
    <div class="row">
      <div class="col-lg-10 offset-lg-1">

        <div class="card-p">

              <div class="flex justify-between items-center pb-2 border-b mb-2">
              <h4 class="font-bold"> {!! trans('articles.showing-article') !!} </h4>
              <div class="float-right">
                <a href="{{ route('articles.index') }}" class="btn btn-light btn-sm float-right">
                  <i class="fa fa-fw fa-mail-reply" aria-hidden="true"></i>
                  {!! trans('articles.buttons.back-to-articles') !!}
                </a>
              </div>
          </div>

          <div class="card-body">

            <div class="row flex justify-center items-center">
              <div class="w-full">
                  <div>
                      <a href="{{ route('articles.edit',[$article->id]) }}" class="btn btn-sm btn-outline-info rounded-full" title="{{ trans('titles.edit') }}">
                        <i class="fa fa-pencil fa-fw" aria-hidden="true"></i> <span> {{ trans('titles.edit') }} </span>
                      </a>
                      {!! Form::open(array('url' => 'articles/' . $article->id, 'class' => 'form-inline', 'title' => trans('titles.delete'))) !!}
                        {!! Form::hidden('_method', 'DELETE') !!}
                        {!! Form::button('<i class="fa fa-trash-o fa-fw" aria-hidden="true"></i> <span>' . trans('titles.delete') . '</span>' , array('class' => 'btn btn-outline-danger rounded-full btn-sm','type' => 'button', 'data-toggle' => 'modal', 'data-target' => '#confirmDelete', 'data-title' => 'Delete Club', 'data-message' => 'Are you sure you want to delete this article?')) !!}
                      {!! Form::close() !!}
                    </div>
              </div>
              <div class="w-full">
                <h3 class="mt-2">
                    {{ $article->title }}
                </h3>
                <h6 class="mt-2">
                    {{ $article->resume ?? '' }}
                </h6>

                @if(count($article->getMedia('article')) > 0)
                  <div class="col-12 px-0">
                    <img src="{{ $article->image }}" alt="{{ $article->title }}" class="rounded center-block mb-3 mt-4">
                  </div>
                @endif
                  
              </div>
            </div>

            <div class="row col-12 px-0">
              @if($article->created_at)
              <div class="text-gray-600 text-sm col-12 px-0">
                  {{ \Carbon\Carbon::createFromFormat('Y-m-d H:i:s',$article->created_at)->format(config('settings.formatDate'))  }}
              </div>
              @endif
              <div class="col-12 pt-2 px-0">
                 {{ $article->body }} 
                </div>
            </div>

          </div>

        </div>
      </div>
    </div>
  </div>

  @include('modals.modal-delete')

@endsection

@section('footer_scripts')
  @include('scripts.delete-modal-script')
@endsection